import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const projectRoot = process.cwd();
const outputPath = path.join(projectRoot, "supabase", "ai_factory_supabase_go_live.sql");

const migrationPaths = [
  "supabase/migrations/202606050001_initial_ai_factory_schema.sql",
  "supabase/migrations/202606050002_sqlite_integer_flags_compatibility.sql",
  "supabase/migrations/202606180001_lock_down_public_data_api.sql"
] as const;

const expectedTables = [
  "auth_users",
  "auth_workspaces",
  "auth_workspace_members",
  "auth_sessions",
  "monitor_categories",
  "monitor_category_creators",
  "keyword_targets",
  "search_queries",
  "sync_runs",
  "collected_contents",
  "search_query_contents",
  "analysis_snapshots",
  "analysis_topics",
  "analysis_evidence_items",
  "analysis_settings",
  "topic_library_entries",
  "drafts",
  "generation_tasks",
  "task_contents",
  "platform_settings",
  "skills",
  "deleted_builtin_skills",
  "skill_files",
  "skill_learning_results",
  "skill_bindings",
  "history_actions",
  "library_entries"
] as const;

function readProjectFile(relativePath: string) {
  return readFileSync(path.join(projectRoot, relativePath), "utf8").replace(/\r\n/g, "\n").trim();
}

function buildVerificationBlock() {
  const tableValues = expectedTables.map((tableName) => `    ('${tableName}')`).join(",\n");

  return `-- ============================================================================\n` +
    `-- Verification block\n` +
    `-- This block intentionally fails if required tables or the private assets bucket are missing.\n` +
    `-- ============================================================================\n\n` +
    `do $$\n` +
    `declare\n` +
    `  missing_tables text;\n` +
    `begin\n` +
    `  with expected(table_name) as (\n` +
    `    values\n` +
    `${tableValues}\n` +
    `  )\n` +
    `  select string_agg(expected.table_name, ', ' order by expected.table_name)\n` +
    `    into missing_tables\n` +
    `  from expected\n` +
    `  where not exists (\n` +
    `    select 1\n` +
    `    from information_schema.tables\n` +
    `    where table_schema = 'public'\n` +
    `      and table_name = expected.table_name\n` +
    `  );\n\n` +
    `  if missing_tables is not null then\n` +
    `    raise exception 'Missing AI Factory tables: %', missing_tables;\n` +
    `  end if;\n\n` +
    `  if not exists (\n` +
    `    select 1\n` +
    `    from storage.buckets\n` +
    `    where id = 'assets'\n` +
    `      and public = false\n` +
    `  ) then\n` +
    `    raise exception 'Missing private Supabase Storage bucket: assets';\n` +
    `  end if;\n` +
    `end $$;\n\n` +
    `select\n` +
    `  'AI Factory Supabase go-live SQL completed' as status,\n` +
    `  count(*) filter (where table_schema = 'public') as public_table_count\n` +
    `from information_schema.tables\n` +
    `where table_name in (${expectedTables.map((tableName) => `'${tableName}'`).join(", ")});\n`;
}

function buildBundle() {
  const sections = migrationPaths.map((relativePath, index) => {
    const content = readProjectFile(relativePath);

    return [
      `-- ============================================================================`,
      `-- ${index + 1}. ${relativePath}`,
      `-- ============================================================================`,
      content
    ].join("\n");
  });

  return [
    `-- AI Content Factory Supabase Go-Live SQL`,
    `-- Generated by: npm run supabase:bundle-sql`,
    `-- Source migrations are listed below in execution order.`,
    `--`,
    `-- Run this entire file once in Supabase SQL Editor for a fresh production project.`,
    `-- It contains only schema/storage/bootstrap SQL and verification queries.`,
    `-- It does not contain API keys, passwords, service-role keys, or user secrets.`,
    ``,
    ...sections,
    buildVerificationBlock()
  ].join("\n\n").trimEnd() + "\n";
}

function main() {
  const nextContent = buildBundle();
  const checkOnly = process.argv.includes("--check");

  if (checkOnly) {
    const currentContent = existsSync(outputPath)
      ? readFileSync(outputPath, "utf8").replace(/\r\n/g, "\n")
      : "";

    if (currentContent !== nextContent) {
      throw new Error(
        "Supabase go-live SQL bundle is out of date. Run npm run supabase:bundle-sql."
      );
    }

    console.log("Supabase go-live SQL bundle is up to date.");
    return;
  }

  writeFileSync(outputPath, nextContent, "utf8");
  console.log(`Wrote ${path.relative(projectRoot, outputPath)}`);
}

main();
